# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: "AP9"
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo "First job is in build stage"
- stage: DeployDev
  jobs:
  - deployment: DevDeployJob
      environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo deploy to Dev
